$ErrorActionPreference = 'Stop'
$siteRoot = Split-Path -Parent $MyInvocation.MyCommand.Path

function Nav([string]$active) {
  $items = @(
    @('Pealeht','/','home'),
    @('Meist','/meist/','meist'),
    @('Tooted','/tooted/','tooted'),
    @('Galerii','/galerii/','galerii'),
    @('Tellimuskeskus','/hinnaparing/','quote'),
    @('Kontakt','/kontakt/','kontakt')
  )
  $productActives = @('tooted','lepp','saun','termo')
  $links = ($items | ForEach-Object { $selected = ($_[2] -eq $active) -or ($_[2] -eq 'tooted' -and $active -in $productActives); $current = if ($selected) {' aria-current="page"'} else {''}; "<a href='$($_[1])'$current>$($_[0])</a>" }) -join "`n"
  return "<header class='site-header'><a class='skip' href='#sisu'>Liigu sisu juurde</a><div class='wrap nav'><a class='brand' href='/' aria-label='Servamatapuit avaleht'><img src='/assets/servamatapuit-logo-tight.png' alt='Servamatapuit'></a><button class='mobile-toggle' aria-label='Ava menüü' aria-expanded='false'>☰</button><nav class='menu' aria-label='Peamenüü'>$links</nav></div></header>"
}

function Footer {
  return @"
<footer class='footer'><div class='wrap footer-line'><span>Copyright © 2026 Servamatapuit.ee</span><span><a href='/kontakt/'>Kontakt</a> · <a href='/privaatsus/'>Privaatsus ja küpsised</a></span></div></footer><script src='/assets/site.js' defer></script>
"@
}

function Page([string]$slug,[string]$title,[string]$description,[string]$active,[string]$body) {
  $dir = if ($slug -eq '') {$siteRoot} else {Join-Path $siteRoot $slug}
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
  $canonical = if ($slug -eq '') {'https://servamatapuit.ee/'} else {"https://servamatapuit.ee/$slug/"}
  $html = @"
<!doctype html><html lang='et'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><meta name='google-site-verification' content='ieFCUeWB4pUqxDX980S_COd47kW6NTU7FPkbfUWJFUU'><meta name='referrer' content='strict-origin-when-cross-origin'><title>$title</title><meta name='description' content='$description'><link rel='canonical' href='$canonical'><meta property='og:title' content='$title'><meta property='og:description' content='$description'><meta property='og:type' content='website'><meta property='og:url' content='$canonical'><meta property='og:image' content='https://servamatapuit.ee/assets/oksavaba-servamata-lepp.jpg'><script type='application/ld+json'>{"@context":"https://schema.org","@graph":[{"@type":"WebSite","@id":"https://servamatapuit.ee/#website","url":"https://servamatapuit.ee/","name":"Servamatapuit","inLanguage":"et"},{"@type":"LocalBusiness","@id":"https://servamatapuit.ee/#business","name":"Strumest OÜ – Servamatapuit","url":"https://servamatapuit.ee/","logo":"https://servamatapuit.ee/assets/servamatapuit-logo-tight.png","image":"https://servamatapuit.ee/assets/oksavaba-servamata-lepp.jpg","telephone":"+37255523176","email":"strumest@hotmail.com","priceRange":"€€","address":{"@type":"PostalAddress","streetAddress":"Saekaatri","addressLocality":"Taganurga","addressRegion":"Viljandi maakond","addressCountry":"EE"}}]}</script><link rel='icon' href='/assets/servamatapuit-logo-tight.png'><link rel='stylesheet' href='/assets/style.css'></head><body>$(Nav $active)<main id='sisu'>$body</main>$(Footer)</body></html>
"@
  Set-Content -LiteralPath (Join-Path $dir 'index.html') -Value $html -Encoding utf8
}

$homeBody = @"
<section class='legacy-hero'><div class='legacy-overlay'></div><div class='wrap legacy-hero-content'><h1>Servamatapuit</h1><p>Pakume kvaliteetseid <strong>servamata lepalauamaterjale</strong>, <strong>profiillaudu</strong> ning <strong>termotöödeldud puidutooteid</strong> ehituse ja sisekujunduse tarbeks. Meie eesmärk on tuua <strong>Eesti looduslähedane ilu</strong> igasse ruumi, hoonesse või aeda.</p><a class='legacy-button' href='/kontakt/'>Kontakt</a></div><div class='pyramid bottom'></div></section>

<section class='legacy-products'><div class='pyramid top'></div><div class='wrap'><div class='legacy-title-row'><h2>Meie tooted:</h2><span>Tooted</span></div><div class='legacy-product-list'><article><h3>✔ Servamata lepalauad</h3><p>Naturaalne, töötlemata ilme – ideaalne rustikaalseks sisekujunduseks ja sauna ehituseks.</p><a href='/servamata-lepp/'>Vaata toodet</a></article><article><h3>✔ Servamata lepaplank</h3><p>Paksem plank, mis sobib saunalava ehituseks, mööblitootmiseks ja siseviimistluseks.</p><a href='/servamata-lepp/'>Vaata toodet</a></article><article><h3>✔ Profiillauad (lepp, Abachi)</h3><p>Erinevad profiilid, viimistlemise võimalus. Sobib sauna ehituseks ja laepaneelideks.</p><a href='/profiil-ja-voodrilauad/'>Vaata toodet</a></article><article><h3>✔ Termotöödeldud materjalid</h3><p>Kuumusega töödeldud, vastupidav ja ilmastikukindel – ideaalne terrasside ja fassaadide jaoks.</p><a href='/termopuit/'>Vaata toodet</a></article></div></div><div class='pyramid bottom'></div></section>

<section class='legacy-portfolio' aria-label='Toodete galerii'><a href='/servamata-lepp/'><img src='/assets/servamata-lepp-saunas.jpeg' alt='Servamata lepp saunas'><span>Servamata lepalauad</span></a><a href='/servamata-lepp/'><img src='/assets/lepaplank-35mm.jpg' alt='Servamata lepaplank'><span>Servamata lepaplank</span></a><a href='/profiil-ja-voodrilauad/'><img src='/assets/lepa-profiillaud.jpg' alt='Lepa profiillaud'><span>Profiillauad</span></a><a href='/termopuit/'><img src='/assets/termoaed-terrass.webp' alt='Termopuidust terrass'><span>Termotöödeldud materjalid</span></a></section>

<section class='legacy-eu'><div class='wrap legacy-eu-grid'><div class='eu-emblem'><img src='/assets/eu-emblem.svg' alt='Euroopa Liidu embleem'><strong>Kaasrahastanud Euroopa Liit</strong></div><div class='eu-copy'><p>Strumest OÜ tegevust on toetanud PRIA läbi Euroopa Maaelu Arengu Põllumajandusfondi (EAFRD). Oleme saanud toetust uute seadmete soetamiseks, mis aitab tõsta toodangu mahtu ning kvaliteeti.</p><p>Soetatud seadmete hulka kuuluvad värvimisautomaat, järkamissaag ning kiletusmasin. Antud seadmed aitavad meil kvaliteetsete siseviimistlusmaterjalide valikut pidevalt laiendada ning jätkuvalt leida igale kliendile sobilik lahendus.</p><a class='legacy-button dark' href='/kontakt/'>Kontakt</a></div></div></section>

<section class='legacy-why'><div class='wrap legacy-why-grid'><div><span class='section-label'>servamatapuit.ee</span><h2>Miks valida just Servamatapuit?</h2></div><ul><li>Üle 10 aasta kogemust puidutööstuses</li><li>Kohalik materjal – keskkonnasõbralik ja jätkusuutlik</li><li>Erimõõdus materjalide lõikamine vastavalt tellimusele</li><li>Paindlik tarne üle Eesti</li><li>Personaalne klienditugi – vastame kiiresti ja professionaalselt</li></ul></div></section>

<section class='legacy-testimonials'><div class='wrap'><h2>Mida kliendid meist räägivad.</h2><div class='testimonial-grid'><blockquote><p>“Tellisin sauna jaoks lavalauad ja olin väga positiivselt üllatunud – materjal oli kuiv, sirge ja täpselt paraja mõõduga. Väga sõbralik teenindus ja kiire tarne!”</p><div class='stars'>★★★★★</div><cite>Kristjan T</cite></blockquote><blockquote><p>“Meie maamajja sobis täiuslikult servamata lepp. Näha oli, et see on korralikult kuivatatud ja käsitsi viimistletud. Hind ja kvaliteet olid väga hästi paigas.”</p><div class='stars'>★★★★★</div><cite>Marika K</cite></blockquote><blockquote><p>“Võtsime fassaadiks termotöödeldud materjali ja tulemus on super! Ka mitme kuu möödudes hoiab see oma kuju ja välimust. Soovitan!”</p><div class='stars'>★★★★★</div><cite>Rainer V</cite></blockquote></div></div></section>

<section class='legacy-cta'><div class='legacy-overlay'></div><div class='pyramid top'></div><div class='wrap legacy-cta-content'><h2>Võta meiega ühendust – leiame parima lahenduse sinu puiduprojektile.</h2><p>Oleme vaid ühe kliki kaugusel. Küsi pakkumist või konsulteeri spetsialistiga.</p><a class='legacy-button' href='/kontakt/'>Kontakt</a></div></section>
"@
Page '' 'Servamata lepp, saunamaterjalid ja termopuit | Servamatapuit' 'Servamata lepp, sauna- ja termopuit sinu projektile. Eesti tootja Strumest OÜ Viljandimaal.' 'home' $homeBody

$productsBody = @"
<section class='hero'><div class='wrap'><span class='eyebrow'>Tooted</span><h1>Puitmaterjalid sinu projekti jaoks</h1><p class='lead'>Vali kategooria või saada mõõtude ja kogusega päring. Aitame leida sobiva lahenduse.</p></div></section><section class='section'><div class='wrap grid two'><article class='card'><img src='/assets/servamata-lepp-saunas.jpeg' alt='Servamata lepp saunas'><div class='card-body'><h2>Servamata lepp</h2><p>Naturaalne, oksavaba ja rustikaalne lepp.</p><a class='card-link' href='/servamata-lepp/'>Vaata valikut →</a></div></article><article class='card'><img src='/assets/lepapuidust-saun.webp' alt='Lepapuidust saun'><div class='card-body'><h2>Saunamaterjalid</h2><p>Abachi, lepp ja termopuit sauna ehituseks.</p><a class='card-link' href='/saunamaterjalid/'>Vaata valikut →</a></div></article><article class='card'><img src='/assets/lepa-profiillaud.jpg' alt='Lepa profiillaud'><div class='card-body'><h2>Profiil- ja voodrilauad</h2><p>STS4 ja SHP profiilid eri puiduliikides.</p><a class='card-link' href='/profiil-ja-voodrilauad/'>Vaata valikut →</a></div></article><article class='card'><img src='/assets/termoaed-aiapaneel.jpg' alt='Termopuidust aiapaneel'><div class='card-body'><h2>Termopuit</h2><p>Terrassid, aiad, põrandamoodulid ja raamid.</p><a class='card-link' href='/termopuit/'>Vaata valikut →</a></div></article></div><div class='notice'><strong>Vaata ka laoleide.</strong> Piiratud koguses eripartiid võivad olla kohe saadaval. <a href='/laoleiud/'>Vaata laoleide →</a></div></div></section>
"@
Page 'tooted' 'Tooted | Servamatapuit' 'Servamata lepp, saunamaterjalid, profiil- ja voodrilauad ning termopuit.' 'tooted' $productsBody

function ProductPage([string]$slug,[string]$title,[string]$intro,[string]$image,[string]$alt,[string]$active,[string]$table,[string]$extra) {
  $body = "<section class='hero'><div class='wrap hero-grid'><div><span class='eyebrow'>Tooted</span><h1>$title</h1><p class='lead'>$intro</p><div class='actions'><a class='btn' href='/hinnaparing/'>Küsi saadavust ja hinda</a></div></div><div class='hero-media'><img src='/assets/$image' alt='$alt'></div></div></section><section class='section'><div class='wrap content'><div class='prose'>$extra<div class='table-wrap'>$table</div><div class='notice'>Puit on looduslik materjal ning toon, laius ja struktuur võivad partiiti erineda. Täpse saadavuse kinnitame pakkumises.</div></div><aside class='sidebox'><h3>Küsi pakkumist</h3><p>Lisa mõõt, kogus ja tarnekoht. Nii saame teha täpse pakkumise.</p><a class='btn' href='/hinnaparing/'>Saada päring</a></aside></div></section>"
  Page $slug "$title | Servamatapuit" $intro $active $body
}

$leppTable = "<table><thead><tr><th>Toode</th><th>Paksus</th><th>Mõõt / pikkus</th><th>Hind</th></tr></thead><tbody><tr><td>Naturaalne servamata lepp</td><td>20 mm</td><td>150–350 × 2000–3000 mm</td><td>15 €/m²</td></tr><tr><td>Oksavaba servamata lepp</td><td>20 mm</td><td>120–250 × 2400–3000 mm</td><td>19 €/m²</td></tr><tr><td>C-sort, rustikaalne</td><td>20 mm</td><td>Valikuline</td><td>7 €/m²</td></tr><tr><td>Lepaplank</td><td>35 mm</td><td>Laius 150–300 mm</td><td>7–12 €/jm</td></tr></tbody></table>"
ProductPage 'servamata-lepp' 'Servamata lepp' 'Kuivatatud, kooritud ja hööveldatud lepp sauna, sisekujundusse, mööbliks ja viimistluseks.' 'servamata-lepp-saunas.jpeg' 'Servamata lepp saunas' 'lepp' $leppTable '<h2>Naturaalne materjal omanäoliseks tulemuseks</h2><p>Servamata serv jätab alles puidu loomuliku joone. Valikus on eri laiuse ja kvaliteediga materjal ning oksavaba sort nõudlikumaks viimistluseks.</p><ul><li>Kuivatatud ja kooritud</li><li>Vajadusel hööveldatud</li><li>Sobib sauna, seina, lae ja mööbli jaoks</li></ul>'

$saunTable = "<table><thead><tr><th>Materjal</th><th>Profiil / mõõt</th><th>Hind</th></tr></thead><tbody><tr><td>Abachi</td><td>STS4 15×145, A-sort</td><td>Küsi pakkumist</td></tr><tr><td>Abachi</td><td>STS4 15×92, A-sort</td><td>Küsi pakkumist</td></tr><tr><td>Abachi</td><td>SHP 26×90 või 26×140</td><td>Küsi pakkumist</td></tr><tr><td>Lepp</td><td>SHP 28×90, 23×130 või 28×125</td><td>Küsi pakkumist</td></tr><tr><td>Termomänd / termokuusk</td><td>Raam 42×92</td><td>3,50 €/jm</td></tr><tr><td>Termomänd / termokuusk</td><td>Raam 42×140</td><td>4,80 €/jm</td></tr></tbody></table>"
ProductPage 'saunamaterjalid' 'Saunamaterjalid' 'Abachi, lepp ja termopuit lavade, seinte ning saunaraamide ehituseks.' 'abachi-saunavooder.webp' 'Abachi saunavooder' 'saun' $saunTable '<h2>Materjalid tervikliku sauna jaoks</h2><p>Aitame valida õige profiili ja puiduliigi vastavalt sellele, kas ehitad lava, seina, lage või raamistikku.</p>'

$profileTable = "<table><thead><tr><th>Puit</th><th>Profiil / mõõt</th><th>Hind</th></tr></thead><tbody><tr><td>Abachi</td><td>STS4 15×145</td><td>Küsi pakkumist</td></tr><tr><td>Abachi</td><td>STS4 15×92, A-sort</td><td>Küsi pakkumist</td></tr><tr><td>Lepp</td><td>STS4 15×92</td><td>Küsi pakkumist</td></tr><tr><td>Lepp</td><td>STS4 15×125, A-sort</td><td>27 €/m²</td></tr><tr><td>Lepp</td><td>SHP 28×90, 23×130 või 28×125</td><td>Küsi pakkumist</td></tr><tr><td>Kask</td><td>STS4 15×92</td><td>10 €/m²</td></tr></tbody></table>"
ProductPage 'profiil-ja-voodrilauad' 'Profiil- ja voodrilauad' 'STS4 ja SHP profiilid abachist, lepast, kasest ning teistest puiduliikidest.' 'lepa-profiillaud.jpg' 'Lepa profiillaud' 'tooted' $profileTable '<h2>Sauna ja siseviimistluse profiilid</h2><p>Valikus on erineva laiuse, paksuse ja sorteerimisega lauad. Küsi täpset laoseisu soovitud mõõdu järgi.</p>'

$termoTable = "<table><thead><tr><th>Toode</th><th>Mõõt</th><th>Hind</th></tr></thead><tbody><tr><td>Terrassilaud, termomänd</td><td>26×117, pikkus kuni 2700</td><td>15 €/m²</td></tr><tr><td>Terrassilaud, termomänd</td><td>26×117, pikkus 3000+</td><td>20 €/m²</td></tr><tr><td>Põrandamoodul</td><td>250×500, 500×500 või 250×1000</td><td>45 €/m²</td></tr><tr><td>Aialipp</td><td>20×62</td><td>Alates 1 €/jm</td></tr><tr><td>Aialipp</td><td>20×112</td><td>Alates 1,80 €/jm</td></tr><tr><td>Aialipp</td><td>20×140</td><td>Alates 2,25 €/jm</td></tr><tr><td>Raam</td><td>42×92 / 42×140</td><td>3,50 / 4,80 €/jm</td></tr></tbody></table>"
ProductPage 'termopuit' 'Termopuit' 'Termotöödeldud terrassilauad, põrandamoodulid, aialipid ja raamimaterjal.' 'termoaed-terrass.webp' 'Termopuidust terrass' 'termo' $termoTable '<h2>Vastupidav puit väli- ja saunalahendusteks</h2><p>Termotöötlus parandab puidu mõõdupüsivust ja vastupidavust. Valikus on terrassid, aiad, moodulid ja raamimaterjal.</p>'

$stockTable = "<table><thead><tr><th>Toode</th><th>Mõõt / pikkus</th><th>Hind</th></tr></thead><tbody><tr><td>Radiata männi voodrilaud STS</td><td>20×138, kuni 4800</td><td>38 €/m²</td></tr><tr><td>Frake SHP</td><td>20×140</td><td>Küsi pakkumist</td></tr><tr><td>Frake STS4</td><td>15×135, kuni 4500</td><td>Küsi pakkumist</td></tr><tr><td>Termohaab STS4</td><td>15×100, pikkus 2100</td><td>30 €/m²</td></tr><tr><td>Mänd STS4</td><td>15×120, pikkus 3000</td><td>15 €/m²</td></tr></tbody></table>"
ProductPage 'laoleiud' 'Laoleiud' 'Piiratud koguses eripartiid ja kohe saadaval puitmaterjalid.' 'radiata-sts-20x138-pealt.jpg' 'Radiata männi profiillaud' 'tooted' $stockTable '<h2>Hea hinnaga piiratud kogused</h2><p>Laoleidude kogused ja pikkused muutuvad kiiresti. Materjali saab sõltuvalt tootest viimistleda või harjata.</p>'

$galleryBody = @"
<section class='hero'><div class='wrap'><span class='eyebrow'>Inspiratsioon</span><h1>Galerii</h1><p class='lead'>Näiteid servamata lepast, saunamaterjalidest ja termopuidu lahendustest.</p></div></section><section class='section'><div class='wrap gallery'><img src='/assets/servamata-lepp-saunas.jpeg' alt='Servamata lepp saunas'><img src='/assets/lepapuidust-saun.webp' alt='Lepapuidust saun'><img src='/assets/termoaed-terrass.webp' alt='Termopuidust terrass'><img src='/assets/servamata-lepp-sisekujunduses.jpg' alt='Servamata lepp sisekujunduses'><img src='/assets/termotoodeldud-puit-saunas.jpg' alt='Termotöödeldud puit saunas'><img src='/assets/termoaed-aiapaneel.jpg' alt='Termopuidust aiapaneel'><img src='/assets/termoaed-porandamoodulid.jpg' alt='Termopuidust põrandamoodulid'><img src='/assets/lepaplank-35mm.jpg' alt='35 mm lepaplank'><img src='/assets/radiata-sts-20x138-pealt.jpg' alt='Radiata männi voodrilaud'></div></section>
"@
Page 'galerii' 'Galerii | Servamatapuit' 'Inspiratsioon servamata lepa, sauna- ja termopuidu kasutamiseks.' 'galerii' $galleryBody

$aboutBody = @"
<section class='hero'><div class='wrap hero-grid'><div><span class='eyebrow'>Meist</span><h1>Üle kümne aasta kogemust puiduga</h1><p class='lead'>Strumest OÜ pakub servamata leppa, sauna- ja termopuitu nii eraklientidele kui ehitajatele.</p></div><div class='hero-media'><img src='/assets/oksavaba-servamata-lepp.jpg' alt='Oksavaba lepapuit'></div></div></section><section class='section'><div class='wrap content'><div class='prose'><h2>Eesti tootja Viljandimaal</h2><p>Tunneme materjali ja aitame valida projekti jaoks sobiva puiduliigi, profiili, mõõdu ning koguse. Meie eesmärk on anda selge vastus saadavuse ja hinna kohta.</p><h2>Miks valida meid?</h2><ul><li>Üle 10 aasta praktilist kogemust</li><li>Lai valik naturaalset ja termotöödeldud puitu</li><li>Paindlikud mõõdud ja kogused</li><li>Otsekontakt Eesti tootjaga</li></ul><p>Ettevõtte arendust on toetanud Euroopa Liit PRIA meetmete kaudu.</p></div><aside class='sidebox'><h3>Strumest OÜ</h3><p>Registrikood 14142376<br>KMKR EE101977362<br>Saekaatri, Taganurga, Viljandi maakond</p><a class='btn' href='/kontakt/'>Võta ühendust</a></aside></div></section>
"@
Page 'meist' 'Meist | Servamatapuit' 'Strumest OÜ on üle kümne aasta kogemusega Eesti puitmaterjalide tootja Viljandimaal.' 'meist' $aboutBody

$contactBody = @"
<section class='hero'><div class='wrap'><span class='eyebrow'>Kontakt</span><h1>Võta ühendust</h1><p class='lead'>Küsi toodete, mõõtude, koguste ja transpordi kohta.</p></div></section><section class='section'><div class='wrap contact-grid'><div><h2>Strumest OÜ</h2><ul class='contact-list'><li><strong>Telefon</strong><br><a href='tel:+37255523176'>+372 5552 3176</a></li><li><strong>E-post</strong><br><a href='mailto:strumest@hotmail.com'>strumest@hotmail.com</a></li><li><strong>Asukoht</strong><br>Saekaatri, Taganurga, Viljandi maakond</li><li><strong>Registrikood</strong><br>14142376</li><li><strong>KMKR</strong><br>EE101977362</li></ul><a class='btn alt' href='https://maps.google.com/?q=Saekaatri%2C+Taganurga%2C+Viljandi+maakond' rel='noopener'>Ava Google Mapsis</a></div><div class='sidebox' style='position:static'><h2>Soovid hinnapakkumist?</h2><p>Kiireima vastuse saad, kui lisad soovitud materjali, mõõdu, koguse ja tarnekoha.</p><a class='btn' href='/hinnaparing/'>Täida päringuvorm</a></div></div></section>
"@
Page 'kontakt' 'Kontakt | Servamatapuit' 'Strumest OÜ kontakt: +372 5552 3176, strumest@hotmail.com, Viljandimaa.' 'kontakt' $contactBody

$privacyBody = @"
<section class='hero'><div class='wrap'><span class='eyebrow'>Privaatsus</span><h1>Privaatsus ja küpsised</h1><p class='lead'>Siin selgitame, milliseid andmeid Servamatapuit.ee kasutamisel töödeldakse ja millised valikud sul on.</p></div></section><section class='section'><div class='wrap content'><div class='prose'><h2>Vastutav töötleja</h2><p>Strumest OÜ, registrikood 14142376, Saekaatri, Taganurga, Viljandi maakond. Privaatsusküsimustes kirjuta aadressile <a href='mailto:strumest@hotmail.com'>strumest@hotmail.com</a>.</p><h2>Hinnapäringud</h2><p>Hinnapäringu saatmisel töötleme sinu nime, e-posti aadressi, telefoninumbrit ja päringu sisu, et päringule vastata, pakkumine koostada ning võimalikku kliendisuhet hallata. Vorm edastatakse FormSubmit teenuse kaudu aadressidele strumest@hotmail.com ja strumest@gmail.com. Päringuandmeid säilitame ainult nii kaua, kui see on vastamiseks, kliendisuhteks või seadusest tulenevate kohustuste täitmiseks vajalik.</p><h2>Analüütika ja reklaamide mõõtmine</h2><p>Kasutame Google Analytics 4 teenust veebilehe kasutuse ja Google Adsi tulemuste mõõtmiseks. Analüütika- ja reklaamiküpsised aktiveeritakse ainult sinu nõusolekul. Kui valid „Ainult vajalikud”, jäävad vastavad salvestusõigused keelatuks. Google’i mõõtmis-ID on G-G5KYTZ3EV7.</p><h2>Vajalik salvestus</h2><p>Brauseri kohalikku salvestusse jääb sinu küpsiste valik, et me ei küsiks seda igal lehevaatamisel uuesti. Seda valikut kasutatakse ainult nõusoleku meelespidamiseks.</p><h2>Sinu õigused</h2><p>Sul on õigus küsida juurdepääsu oma andmetele, nõuda ebaõigete andmete parandamist või kustutamist, piirata töötlemist, esitada vastuväide ning võtta nõusolek tagasi. Taotluse saad saata aadressile <a href='mailto:strumest@hotmail.com'>strumest@hotmail.com</a>. Samuti on sul õigus pöörduda Andmekaitse Inspektsiooni poole.</p><h2>Muuda küpsiste valikut</h2><p><button class='btn alt' type='button' data-manage-consent>Muuda küpsiste valikut</button></p><p><small>Viimati uuendatud 8. oktoobril 2026.</small></p></div><aside class='sidebox'><h3>Kontakt</h3><p>Strumest OÜ<br>Registrikood 14142376<br>Saekaatri, Taganurga<br>Viljandi maakond</p><p><a href='mailto:strumest@hotmail.com'>strumest@hotmail.com</a><br><a href='tel:+37255523176'>+372 5552 3176</a></p></aside></div></section>
"@
Page 'privaatsus' 'Privaatsus ja küpsised | Servamatapuit' 'Servamatapuit.ee privaatsus- ja küpsisteave.' '' $privacyBody

$quoteBody = @"
<section class='hero'><div class='wrap'><span class='eyebrow'>Hinnapäring</span><h1>Küsi pakkumist</h1><p class='lead'>Kirjelda soovitud materjali, mõõtu, kogust ja tarnekohta. Vastame esimesel võimalusel.</p></div></section><section class='section'><div class='wrap contact-grid'><div><h2>Mida päringusse lisada?</h2><ul><li>Toode või puiduliik</li><li>Soovitud mõõt ja kvaliteet</li><li>Kogus</li><li>Tarnekoht</li><li>Soovitud tähtaeg</li></ul><p>Võid ka helistada <a href='tel:+37255523176'><strong>+372 5552 3176</strong></a> või kirjutada <a href='mailto:strumest@hotmail.com'><strong>strumest@hotmail.com</strong></a>.</p></div><form class='form' data-quote-form action='https://formsubmit.co/ajax/strumest@hotmail.com' method='POST'><input type='hidden' name='_subject' value='Uus päring Servamatapuit.ee veebist'><input type='hidden' name='_cc' value='strumest@gmail.com'><input type='hidden' name='_template' value='table'><input type='hidden' name='_captcha' value='false'><input class='trap' tabindex='-1' autocomplete='off' name='_honey' aria-hidden='true'><div class='field'><label for='name'>Nimi *</label><input id='name' name='name' autocomplete='name' required></div><div class='field'><label for='email'>E-post *</label><input id='email' name='email' type='email' autocomplete='email' required></div><div class='field'><label for='phone'>Telefon</label><input id='phone' name='phone' type='tel' autocomplete='tel'></div><div class='field'><label for='product'>Toode või materjal *</label><input id='product' name='Toode või materjal' required></div><div class='field'><label for='details'>Soovitud mõõt, kogus, tarnekoht ja lisainfo *</label><textarea id='details' name='Soovitud mõõt, kogus, tarnekoht ja lisainfo' required></textarea></div><button class='btn' type='submit'>Saada päring</button><p class='status' role='status' aria-live='polite'></p></form></div></section>
"@
Page 'hinnaparing' 'Küsi pakkumist | Servamatapuit' 'Saada Servamatapuidule hinnapäring: materjal, mõõt, kogus ja tarnekoht.' 'quote' $quoteBody

Set-Content -LiteralPath (Join-Path $siteRoot 'CNAME') -Value 'servamatapuit.ee' -Encoding ascii
Set-Content -LiteralPath (Join-Path $siteRoot '.nojekyll') -Value '' -Encoding ascii
Set-Content -LiteralPath (Join-Path $siteRoot 'robots.txt') -Value "User-agent: *`nAllow: /`nSitemap: https://servamatapuit.ee/sitemap.xml" -Encoding ascii
$headers = @"
/*
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Content-Security-Policy: default-src 'self'; script-src 'self' https://www.googletagmanager.com; connect-src 'self' https://formsubmit.co https://www.google-analytics.com https://region1.google-analytics.com; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'; base-uri 'self'; form-action https://formsubmit.co; frame-ancestors 'none'; upgrade-insecure-requests
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=()
"@
Set-Content -LiteralPath (Join-Path $siteRoot '_headers') -Value $headers -Encoding utf8
$urls = @('','tooted','servamata-lepp','saunamaterjalid','profiil-ja-voodrilauad','termopuit','laoleiud','galerii','meist','kontakt','hinnaparing','privaatsus')
$xml = "<?xml version='1.0' encoding='UTF-8'?>`n<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>`n" + (($urls | ForEach-Object { $loc = if ($_ -eq '') {'https://servamatapuit.ee/'} else {"https://servamatapuit.ee/$_/"}; "  <url><loc>$loc</loc></url>" }) -join "`n") + "`n</urlset>"
Set-Content -LiteralPath (Join-Path $siteRoot 'sitemap.xml') -Value $xml -Encoding utf8
Copy-Item -LiteralPath (Join-Path $siteRoot 'index.html') -Destination (Join-Path $siteRoot '404.html') -Force
Write-Host "Built $($urls.Count) pages in $siteRoot"
